Repository 4Subsea/fourinsight-campaigns-python, pull requests merged in 2023-01, with the labels that each got.

#29 Add user agent header to requests
  fourinsight/campaigns/api.py
  tests/conftest.py
  tests/test_api.py
Labels: enhancement

#30 Docs: Expand userguide to include example for client.overview()
  README.rst
  docs/index.rst
  docs/user_guide/access_campaigns.rst
  fourinsight/campaigns/api.py
Labels: documentation

#32 DST-389 Remove references to partial URLs in fourinsight.campaigns
  fourinsight/campaigns/api.py
  tests/conftest.py
  tests/test_api.py
Labels: refactor
